namespace CrashEvidenceCollector.Core;

/// <summary>
/// Broad grouping for a stop code, so incidents can be counted, coloured and
/// filtered by the part of Windows that reported them rather than by raw number.
/// The family says who <em>detected</em> the fault; it never claims who caused it.
/// </summary>
public enum BugCheckFamily
{
    Unknown,
    Memory,
    Driver,
    Storage,
    FileSystem,
    Hardware,
    Graphics,
    Power,
    Security,
    Boot,
    Process,
    Network,
    Usb,
    Virtualization,
    Verifier,
    Kernel
}

/// <summary>A stop code with a name, a plain-English title and one honest sentence.</summary>
public sealed record BugCheckSummary(ulong Code, string Name, string PlainTitle, string Meaning, BugCheckFamily Family)
{
    public string HexCode => $"0x{Code:X}";
}

/// <summary>
/// Breadth-first stop-code vocabulary. <see cref="BugCheckKnowledge"/> holds the
/// deep, parameter-level analysis for the codes this app can genuinely reason
/// about; this catalogue exists so that every <em>other</em> code still gets a
/// name and a sentence instead of raw hexadecimal.
///
/// Entries state documented Windows semantics only. Where a name is misleading
/// — MEMORY_MANAGEMENT does not mean "your RAM is faulty" — the sentence says so,
/// because the wrong plain-English answer is worse than none.
/// </summary>
public static class BugCheckCatalog
{
    private static BugCheckSummary B(ulong code, string name, string title, string meaning, BugCheckFamily family) => new(code, name, title, meaning, family);

    private static readonly IReadOnlyDictionary<ulong, BugCheckSummary> Catalog = new BugCheckSummary[]
    {
        B(0x01, "APC_INDEX_MISMATCH", "Asynchronous call bookkeeping went out of balance", "A driver or system call entered and left a critical region an unequal number of times.", BugCheckFamily.Kernel),
        B(0x02, "DEVICE_QUEUE_NOT_BUSY", "A device queue was in an impossible state", "The kernel found a device queue marked idle while work was still outstanding.", BugCheckFamily.Driver),
        B(0x03, "INVALID_AFFINITY_SET", "A thread was pinned to processors that do not exist", "Code requested a processor affinity mask that no processor on this machine matches.", BugCheckFamily.Kernel),
        B(0x04, "INVALID_DATA_ACCESS_TRAP", "The processor trapped an invalid data access", "A data access trap occurred that the kernel could not resolve.", BugCheckFamily.Kernel),
        B(0x05, "INVALID_PROCESS_ATTACH_ATTEMPT", "Code attached to a process illegally", "A thread tried to attach to another process's address space while already attached or holding locks.", BugCheckFamily.Kernel),
        B(0x06, "INVALID_PROCESS_DETACH_ATTEMPT", "Code detached from a process it was not attached to", "A thread tried to leave a process address space it had never entered.", BugCheckFamily.Kernel),
        B(0x07, "INVALID_SOFTWARE_INTERRUPT", "An invalid software interrupt was raised", "Kernel code raised a software interrupt that is not valid on this processor.", BugCheckFamily.Kernel),
        B(0x08, "IRQL_NOT_DISPATCH_LEVEL", "Interrupt level was wrong for the operation", "Code ran at an interrupt level other than the one the operation required.", BugCheckFamily.Kernel),
        B(0x09, "IRQL_NOT_GREATER_OR_EQUAL", "Interrupt level was too low for the operation", "Code performed an operation that requires a raised interrupt level while running below it.", BugCheckFamily.Kernel),
        B(0x0A, "IRQL_NOT_LESS_OR_EQUAL", "Kernel code touched memory it could not touch there", "Kernel-mode code accessed invalid or pageable memory at an interrupt level where that is forbidden; a driver defect, a freed pointer or earlier corruption can all produce it.", BugCheckFamily.Driver),
        B(0x0B, "NO_EXCEPTION_HANDLING_SUPPORT", "Exception handling was unavailable", "Windows could not initialise exception handling support.", BugCheckFamily.Kernel),
        B(0x0C, "MAXIMUM_WAIT_OBJECTS_EXCEEDED", "A thread waited on too many objects", "Code exceeded the maximum number of objects a single wait can cover.", BugCheckFamily.Kernel),
        B(0x0D, "MUTEX_LEVEL_NUMBER_VIOLATION", "Locks were taken in the wrong order", "Mutexes were acquired out of their declared ranking order, which risks deadlock.", BugCheckFamily.Kernel),
        B(0x0E, "NO_USER_MODE_CONTEXT", "A thread had no user-mode context to return to", "The kernel tried to return to user mode from a thread that has none.", BugCheckFamily.Kernel),
        B(0x0F, "SPIN_LOCK_ALREADY_OWNED", "A lock was acquired twice by the same code", "A spin lock was requested by a processor that already held it — a classic deadlock.", BugCheckFamily.Kernel),
        B(0x10, "SPIN_LOCK_NOT_OWNED", "A lock was released that was never held", "A spin lock was released by code that did not own it.", BugCheckFamily.Kernel),
        B(0x11, "THREAD_NOT_MUTEX_OWNER", "A lock was released by the wrong thread", "A mutex was released by a thread other than the one that acquired it.", BugCheckFamily.Kernel),
        B(0x12, "TRAP_CAUSE_UNKNOWN", "The processor raised a trap Windows could not identify", "An unrecognised processor trap occurred; the trap number in the parameters is the useful evidence.", BugCheckFamily.Hardware),
        B(0x13, "EMPTY_THREAD_REAPER_LIST", "Thread cleanup found an empty list", "The thread reaper was signalled with nothing to clean up.", BugCheckFamily.Kernel),
        B(0x18, "REFERENCE_BY_POINTER", "An object's reference count was wrong", "An object's reference count dropped to an impossible value, usually from a driver releasing a reference it did not hold.", BugCheckFamily.Driver),
        B(0x19, "BAD_POOL_HEADER", "Kernel memory bookkeeping was corrupted", "The header of a kernel memory allocation was damaged. The code that detected the damage is usually not the code that caused it.", BugCheckFamily.Memory),
        B(0x1A, "MEMORY_MANAGEMENT", "Windows found its own memory records in an impossible state", "Page tables, PTEs or the PFN database were inconsistent. Despite the name this does not prove faulty RAM — drivers, paging storage and CPU instability can all produce it, and the memory manager is usually the victim rather than the culprit.", BugCheckFamily.Memory),
        B(0x1B, "PFN_SHARE_COUNT", "A physical page's share count was wrong", "The memory manager found a page-frame share count it considers impossible.", BugCheckFamily.Memory),
        B(0x1D, "NO_SPINLOCK_AVAILABLE", "No lock was available", "The kernel exhausted a fixed pool of spin locks.", BugCheckFamily.Kernel),
        B(0x1E, "KMODE_EXCEPTION_NOT_HANDLED", "Kernel code hit an error nothing caught", "An exception was raised in kernel mode and no handler dealt with it. Parameter 1 is the exception itself and is the first thing to decode.", BugCheckFamily.Kernel),
        B(0x20, "KERNEL_APC_PENDING_DURING_EXIT", "A thread exited with work still queued", "A thread terminated while an asynchronous procedure call was still pending, normally a driver failing to balance its own calls.", BugCheckFamily.Driver),
        B(0x21, "QUOTA_UNDERFLOW", "A process returned more quota than it used", "Quota accounting for a process went negative.", BugCheckFamily.Kernel),
        B(0x22, "FILE_SYSTEM", "A file system driver hit a fatal condition", "A file system reported a condition it could not safely continue from.", BugCheckFamily.FileSystem),
        B(0x23, "FAT_FILE_SYSTEM", "The FAT file system hit a fatal condition", "The FAT driver found a structure it could not handle; disk health and cabling are relevant evidence.", BugCheckFamily.FileSystem),
        B(0x24, "NTFS_FILE_SYSTEM", "The NTFS file system hit a fatal condition", "The NTFS driver found a condition it could not safely handle. Disk health, cabling and filter drivers are all relevant.", BugCheckFamily.FileSystem),
        B(0x25, "NPFS_FILE_SYSTEM", "The named-pipe file system hit a fatal condition", "The named-pipe driver encountered an unrecoverable internal state.", BugCheckFamily.FileSystem),
        B(0x26, "CDFS_FILE_SYSTEM", "The CD file system hit a fatal condition", "The CD/DVD file system driver encountered an unrecoverable state, often from unreadable media.", BugCheckFamily.FileSystem),
        B(0x27, "RDR_FILE_SYSTEM", "The network redirector hit a fatal condition", "The SMB network redirector encountered an unrecoverable internal state.", BugCheckFamily.Network),
        B(0x28, "CORRUPT_ACCESS_TOKEN", "A security token was corrupted", "An access token was found in an invalid state.", BugCheckFamily.Security),
        B(0x29, "SECURITY_SYSTEM", "The security subsystem hit a fatal condition", "A security component reported an unrecoverable internal error.", BugCheckFamily.Security),
        B(0x2A, "INCONSISTENT_IRP", "An I/O request packet was inconsistent", "An IRP was found in a state inconsistent with the operation being performed on it.", BugCheckFamily.Driver),
        B(0x2B, "PANIC_STACK_SWITCH", "The kernel stack overflowed during a panic", "The kernel ran out of stack while already handling a fatal error, often from very deep driver nesting.", BugCheckFamily.Kernel),
        B(0x2C, "PORT_DRIVER_INTERNAL", "A port driver hit an internal error", "A port driver reported an unrecoverable internal condition.", BugCheckFamily.Driver),
        B(0x2D, "SCSI_DISK_DRIVER_INTERNAL", "The SCSI disk driver hit an internal error", "The SCSI disk class driver reported an unrecoverable internal condition.", BugCheckFamily.Storage),
        B(0x2E, "DATA_BUS_ERROR", "A memory parity or bus error was reported", "The system detected a parity error in memory or on the bus. This one genuinely does point at hardware — RAM, the memory controller or a failing add-in card.", BugCheckFamily.Hardware),
        B(0x2F, "INSTRUCTION_BUS_ERROR", "A bus error occurred fetching an instruction", "The processor could not fetch an instruction because of a bus error.", BugCheckFamily.Hardware),
        B(0x30, "SET_OF_INVALID_CONTEXT", "A thread's stack pointer was set invalid", "Code set a stack pointer to a value outside the thread's valid stack.", BugCheckFamily.Kernel),
        B(0x31, "PHASE0_INITIALIZATION_FAILED", "Windows failed very early in startup", "Startup failed before most of the system was initialised; the cause is usually firmware, boot drivers or damaged system files.", BugCheckFamily.Boot),
        B(0x32, "PHASE1_INITIALIZATION_FAILED", "Windows failed during startup", "System initialisation failed in its second phase.", BugCheckFamily.Boot),
        B(0x33, "UNEXPECTED_INITIALIZATION_CALL", "An initialisation routine was called twice", "A component was asked to initialise at a point where that is not valid.", BugCheckFamily.Boot),
        B(0x34, "CACHE_MANAGER", "The file cache manager hit a fatal condition", "The cache manager could not continue, commonly under memory or paging pressure.", BugCheckFamily.Memory),
        B(0x35, "NO_MORE_IRP_STACK_LOCATIONS", "A driver stack was deeper than allowed", "A driver passed an I/O request further down the stack than the request was built for; typically a filter driver inserted late.", BugCheckFamily.Driver),
        B(0x36, "DEVICE_REFERENCE_COUNT_NOT_ZERO", "A device was deleted while still in use", "A driver deleted a device object that still had outstanding references.", BugCheckFamily.Driver),
        B(0x37, "FLOPPY_INTERNAL_ERROR", "The floppy driver hit an internal error", "The floppy disk driver reported an unrecoverable internal condition.", BugCheckFamily.Storage),
        B(0x38, "SERIAL_DRIVER_INTERNAL", "The serial driver hit an internal error", "The serial port driver reported an unrecoverable internal condition.", BugCheckFamily.Driver),
        B(0x39, "SYSTEM_EXIT_OWNED_MUTEX", "A thread exited still holding a lock", "A thread terminated while it still owned a mutex, leaving other threads unable to proceed.", BugCheckFamily.Kernel),
        B(0x3B, "SYSTEM_SERVICE_EXCEPTION", "An error occurred crossing into the kernel", "An exception occurred while Windows was carrying out a system service on behalf of a program. The program named in the dump is the context, not automatically the cause.", BugCheckFamily.Kernel),
        B(0x3D, "INTERRUPT_EXCEPTION_NOT_HANDLED", "An interrupt handler hit an error nothing caught", "An exception occurred inside interrupt processing and was not handled.", BugCheckFamily.Driver),
        B(0x3E, "MULTIPROCESSOR_CONFIGURATION_NOT_SUPPORTED", "The processor configuration is unsupported", "The processors in this machine are not symmetric in a way Windows requires.", BugCheckFamily.Hardware),
        B(0x3F, "NO_MORE_SYSTEM_PTES", "Windows ran out of address-mapping entries", "System page-table entries were exhausted, usually by a driver leaking mappings over a long uptime.", BugCheckFamily.Memory),
        B(0x40, "TARGET_MDL_TOO_SMALL", "A memory descriptor was too small", "A driver supplied a memory descriptor list smaller than the transfer required.", BugCheckFamily.Driver),
        B(0x41, "MUST_SUCCEED_POOL_EMPTY", "A guaranteed memory request could not be met", "The kernel could not satisfy an allocation that is not allowed to fail.", BugCheckFamily.Memory),
        B(0x44, "MULTIPLE_IRP_COMPLETE_REQUESTS", "A driver completed the same request twice", "Two drivers each reported the same I/O request complete — a driver defect, and the second completer is usually not the offender.", BugCheckFamily.Driver),
        B(0x45, "INSUFFICIENT_SYSTEM_MAP_REGS", "Not enough map registers were available", "A DMA transfer could not obtain the mapping registers it required.", BugCheckFamily.Driver),
        B(0x48, "CANCEL_STATE_IN_COMPLETED_IRP", "A completed request was still marked cancellable", "A driver left a cancel routine attached to a request it had already completed.", BugCheckFamily.Driver),
        B(0x49, "PAGE_FAULT_WITH_INTERRUPTS_OFF", "Memory was paged in with interrupts disabled", "A page fault occurred while interrupts were disabled, which Windows cannot service.", BugCheckFamily.Kernel),
        B(0x4A, "IRQL_GT_ZERO_AT_SYSTEM_SERVICE", "A system call returned at a raised interrupt level", "Code returned from a system service without restoring the interrupt level it started at.", BugCheckFamily.Driver),
        B(0x4C, "FATAL_UNHANDLED_HARD_ERROR", "An unrecoverable system error occurred", "Windows encountered a hard error during startup or shutdown that it could not report normally.", BugCheckFamily.Kernel),
        B(0x4D, "NO_PAGES_AVAILABLE", "Windows ran out of usable memory pages", "No free physical pages remained, typically after a driver leak or extreme memory pressure.", BugCheckFamily.Memory),
        B(0x4E, "PFN_LIST_CORRUPT", "The list of physical memory pages was corrupted", "The page-frame database was found damaged. A driver passing a bad memory descriptor is the common cause; failing RAM is another.", BugCheckFamily.Memory),
        B(0x50, "PAGE_FAULT_IN_NONPAGED_AREA", "Kernel code read memory that was not there", "Memory that should always have been resident was invalid. Freed pointers, driver defects and earlier corruption all produce this; it does not by itself prove faulty RAM.", BugCheckFamily.Memory),
        B(0x51, "REGISTRY_ERROR", "The registry could not be read or written", "A registry operation failed at a level Windows cannot continue from; the hive files on disk, and the disk itself, are the evidence to check.", BugCheckFamily.Storage),
        B(0x52, "MAILSLOT_FILE_SYSTEM", "The mailslot file system hit a fatal condition", "The mailslot driver encountered an unrecoverable internal state.", BugCheckFamily.FileSystem),
        B(0x54, "LM_SERVER_INTERNAL_ERROR", "The file server service hit an internal error", "The LAN Manager server component reported an unrecoverable condition.", BugCheckFamily.Network),
        B(0x55, "DATA_COHERENCY_EXCEPTION", "Processor caches disagreed about memory", "A cache coherency violation was detected between processors — a hardware-level symptom.", BugCheckFamily.Hardware),
        B(0x57, "XNS_INTERNAL_ERROR", "An internal networking error occurred", "A legacy network component reported an unrecoverable condition.", BugCheckFamily.Network),
        B(0x58, "FTDISK_INTERNAL_ERROR", "The fault-tolerant disk driver hit an error", "A mirrored or spanned volume was in an inconsistent state at boot.", BugCheckFamily.Storage),
        B(0x5A, "CRITICAL_SERVICE_FAILED", "A service Windows cannot start without failed", "A boot-critical service failed to start; recent driver or update changes are the first thing to check.", BugCheckFamily.Boot),
        B(0x5C, "HAL_INITIALIZATION_FAILED", "The hardware abstraction layer failed to start", "The HAL could not initialise, which usually points at firmware or a fundamental hardware configuration problem.", BugCheckFamily.Boot),
        B(0x5D, "HEAP_INITIALIZATION_FAILED", "Kernel memory could not be initialised", "The kernel heap failed to initialise during startup.", BugCheckFamily.Boot),
        B(0x5E, "OBJECT_INITIALIZATION_FAILED", "The object manager failed to start", "Core kernel object services could not be initialised.", BugCheckFamily.Boot),
        B(0x5F, "SECURITY_INITIALIZATION_FAILED", "Security services failed to start", "The security subsystem could not be initialised during startup.", BugCheckFamily.Boot),
        B(0x60, "PROCESS_INITIALIZATION_FAILED", "Process management failed to start", "Process services could not be initialised during startup.", BugCheckFamily.Boot),
        B(0x6B, "PROCESS1_INITIALIZATION_FAILED", "The first user process failed to start", "Windows could not start its first user-mode process; missing or damaged system files and storage faults are the usual causes.", BugCheckFamily.Boot),
        B(0x74, "BAD_SYSTEM_CONFIG_INFO", "System configuration data is damaged", "The SYSTEM registry hive or boot configuration is damaged or incomplete.", BugCheckFamily.Boot),
        B(0x76, "PROCESS_HAS_LOCKED_PAGES", "A process exited with memory still locked", "A driver failed to release memory it had locked on behalf of a process that has now ended.", BugCheckFamily.Driver),
        B(0x77, "KERNEL_STACK_INPAGE_ERROR", "Windows could not read a thread's stack from disk", "A required page could not be read back from the paging file. Storage, cabling and controller errors are the primary evidence.", BugCheckFamily.Storage),
        B(0x78, "PHASE0_EXCEPTION", "An error occurred very early in startup", "An exception occurred during the earliest phase of system initialisation.", BugCheckFamily.Boot),
        B(0x79, "MISMATCHED_HAL", "System files do not match the hardware layer", "The hardware abstraction layer and kernel files are from different builds, or firmware changed underneath them.", BugCheckFamily.Boot),
        B(0x7A, "KERNEL_DATA_INPAGE_ERROR", "Windows could not read data it needed from disk", "A required kernel page could not be read from the paging file or disk. Parameter 2 carries the underlying I/O status and is the useful detail; storage health is the first thing to look at.", BugCheckFamily.Storage),
        B(0x7B, "INACCESSIBLE_BOOT_DEVICE", "Windows could not reach the drive it boots from", "The boot volume was unreachable at startup — a changed storage controller mode, a missing driver, or a failing disk.", BugCheckFamily.Storage),
        B(0x7D, "INSTALL_MORE_MEMORY", "There is not enough RAM to start Windows", "Windows found too little usable physical memory to start.", BugCheckFamily.Memory),
        B(0x7E, "SYSTEM_THREAD_EXCEPTION_NOT_HANDLED", "A system thread hit an error nothing caught", "A kernel thread raised an exception with no handler. Parameter 1 is the exception and parameter 2 the address — those two decide where to look.", BugCheckFamily.Kernel),
        B(0x7F, "UNEXPECTED_KERNEL_MODE_TRAP", "The processor raised a trap the kernel could not handle", "Parameter 1 is the trap number: 0x8 is a double fault, usually stack exhaustion or corruption. This is often, but not always, a hardware or overclocking symptom.", BugCheckFamily.Hardware),
        B(0x80, "NMI_HARDWARE_FAILURE", "The hardware raised a non-maskable interrupt", "A hardware component signalled an unrecoverable fault directly to the processor. Memory and add-in cards are the usual sources.", BugCheckFamily.Hardware),
        B(0x81, "SPIN_LOCK_INIT_FAILURE", "Lock initialisation failed at startup", "Kernel spin lock initialisation failed during startup.", BugCheckFamily.Boot),
        B(0x8E, "KERNEL_MODE_EXCEPTION_NOT_HANDLED", "Kernel code hit an error nothing caught", "The 32-bit counterpart of 0x1E: a kernel exception with no handler.", BugCheckFamily.Kernel),
        B(0x92, "UP_DRIVER_ON_MP_SYSTEM", "A single-processor driver loaded on a multi-processor machine", "A driver built for uniprocessor systems was loaded on a multi-processor machine.", BugCheckFamily.Driver),
        B(0x93, "INVALID_KERNEL_HANDLE", "Code closed a handle it should not have", "A protected or already-closed kernel handle was closed.", BugCheckFamily.Kernel),
        B(0x94, "KERNEL_STACK_LOCKED_AT_EXIT", "A thread exited with its stack locked", "A thread terminated while its kernel stack was still locked in memory.", BugCheckFamily.Kernel),
        B(0x96, "INVALID_WORK_QUEUE_ITEM", "A queued work item was invalid", "A work item was removed from a queue in an invalid state, commonly a driver freeing it too early.", BugCheckFamily.Driver),
        B(0x9A, "SYSTEM_LICENSE_VIOLATION", "A licensing check failed", "Windows detected a licensing or trial violation.", BugCheckFamily.Kernel),
        B(0x9B, "UDFS_FILE_SYSTEM", "The UDF file system hit a fatal condition", "The UDF driver encountered an unrecoverable state, commonly from damaged optical media.", BugCheckFamily.FileSystem),
        B(0x9C, "MACHINE_CHECK_EXCEPTION", "The processor reported a hardware error", "The CPU's own error reporting raised an unrecoverable machine check. This is a hardware-level report — the bank and status values name where in the processor it was detected.", BugCheckFamily.Hardware),
        B(0x9E, "USER_MODE_HEALTH_MONITOR", "A critical user-mode process stopped responding", "A monitored user-mode process failed to respond in time, most often on a clustered or server system.", BugCheckFamily.Process),
        B(0x9F, "DRIVER_POWER_STATE_FAILURE", "A driver stalled going to or from sleep", "A driver failed to complete a power transition in time. Parameter 1 selects the layout: subtype 3 means a device blocked a power request, and parameter 4 is that blocked request.", BugCheckFamily.Power),
        B(0xA0, "INTERNAL_POWER_ERROR", "The power manager hit a fatal condition", "The power subsystem encountered a state it could not continue from, often during hibernation or resume.", BugCheckFamily.Power),
        B(0xA1, "PCI_BUS_DRIVER_INTERNAL", "The PCI bus driver hit an internal error", "The PCI bus driver detected an inconsistency, often in firmware-supplied resource assignments.", BugCheckFamily.Hardware),
        B(0xA2, "MEMORY_IMAGE_CORRUPT", "A loaded system image was corrupted in memory", "The in-memory copy of a system image no longer matches what was loaded.", BugCheckFamily.Memory),
        B(0xA3, "ACPI_DRIVER_INTERNAL", "The ACPI driver hit an internal error", "The ACPI driver found firmware behaviour it could not handle.", BugCheckFamily.Hardware),
        B(0xA5, "ACPI_BIOS_ERROR", "The firmware is not ACPI-compliant in a way Windows needs", "The system firmware provided ACPI data Windows could not work with. A BIOS/UEFI update is the usual remedy.", BugCheckFamily.Hardware),
        B(0xA7, "BAD_EXHANDLE", "A handle table entry was corrupted", "The kernel found a handle table entry with an invalid reference count.", BugCheckFamily.Kernel),
        B(0xAB, "SESSION_HAS_VALID_POOL_ON_EXIT", "A session ended with memory still allocated", "A terminal session ended while a driver still held session memory — a leak in a session-space driver.", BugCheckFamily.Memory),
        B(0xAC, "HAL_MEMORY_ALLOCATION", "The hardware layer could not allocate memory", "The HAL could not obtain memory it required, usually very early in startup.", BugCheckFamily.Boot),
        B(0xB1, "BGI_DETECTED_VIOLATION", "A graphics integrity check failed", "The background graphics integrity check detected a violation.", BugCheckFamily.Graphics),
        B(0xB4, "VIDEO_DRIVER_INIT_FAILURE", "Windows could not start in graphics mode", "The display driver failed to initialise, so Windows could not switch out of text mode.", BugCheckFamily.Graphics),
        B(0xB8, "ATTEMPTED_SWITCH_FROM_DPC", "A driver tried to wait during high-priority work", "A deferred procedure call attempted an illegal thread switch — a driver defect.", BugCheckFamily.Driver),
        B(0xB9, "CHIPSET_DETECTED_ERROR", "The chipset reported an error", "The chipset signalled an error condition to the operating system.", BugCheckFamily.Hardware),
        B(0xBA, "SESSION_HAS_VALID_VIEWS_ON_EXIT", "A session ended with memory still mapped", "A terminal session ended while mapped views remained, indicating a driver leak.", BugCheckFamily.Memory),
        B(0xBB, "NETWORK_BOOT_INITIALIZATION_FAILED", "Network boot failed", "Windows could not initialise a network boot.", BugCheckFamily.Network),
        B(0xBE, "ATTEMPTED_WRITE_TO_READONLY_MEMORY", "A driver wrote to memory marked read-only", "A driver attempted to write to a read-only page. The address in parameter 1 identifies the target.", BugCheckFamily.Driver),
        B(0xBF, "MUTEX_ALREADY_OWNED", "A thread took a lock it already held", "A thread attempted to acquire a mutex it already owned.", BugCheckFamily.Kernel),
        B(0xC1, "SPECIAL_POOL_DETECTED_MEMORY_CORRUPTION", "Driver Verifier caught memory corruption", "Special pool detected a driver writing outside its allocation — this names the offending driver directly.", BugCheckFamily.Verifier),
        B(0xC2, "BAD_POOL_CALLER", "A driver made an invalid memory request", "Kernel code made an invalid pool request, such as freeing memory twice or freeing an address it never allocated. Parameter 1 identifies which mistake.", BugCheckFamily.Driver),
        B(0xC4, "DRIVER_VERIFIER_DETECTED_VIOLATION", "Driver Verifier caught a driver breaking the rules", "Verifier deliberately crashed the system on a driver rule violation. Parameter 1 identifies the rule, and the named driver is genuinely the offender.", BugCheckFamily.Verifier),
        B(0xC5, "DRIVER_CORRUPTED_EXPOOL", "A driver corrupted kernel memory", "Kernel pool was corrupted at a raised interrupt level. Driver Verifier is the standard way to identify which driver.", BugCheckFamily.Driver),
        B(0xC6, "DRIVER_CAUGHT_MODIFYING_FREED_POOL", "A driver used memory after freeing it", "A driver wrote to memory it had already released — verifier caught it in the act.", BugCheckFamily.Verifier),
        B(0xC7, "TIMER_OR_DPC_INVALID", "A timer or queued call was in invalid memory", "A kernel timer or deferred call was found in pageable or freed memory, usually because its driver unloaded without cancelling it.", BugCheckFamily.Driver),
        B(0xC8, "IRQL_UNEXPECTED_VALUE", "The interrupt level changed unexpectedly", "The processor's interrupt level was not what the kernel expected, indicating a driver changed it without restoring it.", BugCheckFamily.Driver),
        B(0xC9, "DRIVER_VERIFIER_IOMANAGER_VIOLATION", "Driver Verifier caught an I/O rule violation", "Verifier's I/O manager checks found a driver mishandling an I/O request. Parameter 1 identifies the rule broken.", BugCheckFamily.Verifier),
        B(0xCA, "PNP_DETECTED_FATAL_ERROR", "Plug and Play found a driver behaving illegally", "The Plug and Play manager detected a fatal driver error, such as a duplicate device or an invalid device relation.", BugCheckFamily.Driver),
        B(0xCB, "DRIVER_LEFT_LOCKED_PAGES_IN_PROCESS", "A driver leaked locked memory", "A driver unloaded without releasing pages it had locked.", BugCheckFamily.Driver),
        B(0xCC, "PAGE_FAULT_IN_FREED_SPECIAL_POOL", "A driver used memory after freeing it", "Code referenced memory that special pool had already released.", BugCheckFamily.Verifier),
        B(0xCD, "PAGE_FAULT_BEYOND_END_OF_ALLOCATION", "A driver read or wrote past the end of its memory", "Code accessed memory immediately beyond an allocation — a buffer overrun caught by special pool.", BugCheckFamily.Verifier),
        B(0xCE, "DRIVER_UNLOADED_WITHOUT_CANCELLING_PENDING_OPERATIONS", "A driver unloaded with work still outstanding", "A driver was unloaded while timers, DPCs or worker items it owned were still queued. The named driver is the offender.", BugCheckFamily.Driver),
        B(0xCF, "TERMINAL_SERVER_DRIVER_MADE_INCORRECT_MEMORY_REFERENCE", "A session driver accessed memory incorrectly", "A terminal-server driver referenced memory it should not have.", BugCheckFamily.Driver),
        B(0xD0, "DRIVER_CORRUPTED_MMPOOL", "A driver corrupted memory-manager pool", "A driver damaged memory-manager pool at a raised interrupt level.", BugCheckFamily.Driver),
        B(0xD1, "DRIVER_IRQL_NOT_LESS_OR_EQUAL", "A driver touched memory it could not touch there", "The driver-focused counterpart of 0x0A: a driver accessed invalid or pageable memory at a raised interrupt level. Parameter 4 is the faulting instruction, and the module containing it is the strong lead.", BugCheckFamily.Driver),
        B(0xD3, "DRIVER_PORTION_MUST_BE_NONPAGED", "A driver put code in pageable memory that must stay resident", "A driver accessed pageable memory at a raised interrupt level because part of it was marked pageable that should not be.", BugCheckFamily.Driver),
        B(0xD4, "SYSTEM_SCAN_AT_RAISED_IRQL_CAUGHT_IMPROPER_DRIVER_UNLOAD", "A driver unloaded incorrectly", "A driver unloaded without cleaning up, and the kernel found the remains at a raised interrupt level.", BugCheckFamily.Driver),
        B(0xD5, "DRIVER_PAGE_FAULT_IN_FREED_SPECIAL_POOL", "A driver used memory after freeing it", "A driver referenced special pool memory it had already freed. The named driver is the offender.", BugCheckFamily.Verifier),
        B(0xD6, "DRIVER_PAGE_FAULT_BEYOND_END_OF_ALLOCATION", "A driver ran past the end of its memory", "A driver accessed memory beyond the end of its allocation — a buffer overrun caught by verifier.", BugCheckFamily.Verifier),
        B(0xD8, "DRIVER_USED_EXCESSIVE_PTES", "A driver exhausted address-mapping entries", "A driver consumed so many system page-table entries that none remained.", BugCheckFamily.Driver),
        B(0xDA, "SYSTEM_PTE_MISUSE", "A driver misused address-mapping entries", "A driver used system page-table entries in a way the memory manager forbids.", BugCheckFamily.Driver),
        B(0xDB, "DRIVER_CORRUPTED_SYSPTES", "A driver corrupted address-mapping entries", "System page-table entries were damaged by a driver writing out of bounds.", BugCheckFamily.Driver),
        B(0xDC, "DRIVER_INVALID_STACK_ACCESS", "A driver accessed another thread's stack", "A driver referenced a stack outside the current thread's own.", BugCheckFamily.Driver),
        B(0xDE, "POOL_CORRUPTION_IN_FILE_AREA", "A driver corrupted memory used for file data", "A driver overwrote pool memory that the file system was using.", BugCheckFamily.FileSystem),
        B(0xDF, "IMPERSONATING_WORKER_THREAD", "A worker thread was left impersonating", "A work item returned while still impersonating another security context.", BugCheckFamily.Security),
        B(0xE0, "ACPI_BIOS_FATAL_ERROR", "The firmware reported a fatal condition", "System firmware reported a fatal error, commonly a thermal or hardware fault it wants Windows to stop for.", BugCheckFamily.Hardware),
        B(0xE1, "WORKER_THREAD_RETURNED_AT_BAD_IRQL", "A work item returned at the wrong interrupt level", "A worker routine returned without restoring the interrupt level it was called at.", BugCheckFamily.Driver),
        B(0xE2, "MANUALLY_INITIATED_CRASH", "Someone deliberately crashed this machine", "The crash was triggered on purpose — by the keyboard crash key, a debugger, or a test tool. It is not a fault.", BugCheckFamily.Kernel),
        B(0xE3, "RESOURCE_NOT_OWNED", "A lock was released that was never held", "A thread released an executive resource it did not own.", BugCheckFamily.Kernel),
        B(0xE4, "WORKER_INVALID", "An invalid work item was queued", "Code queued a work item from pageable or invalid memory.", BugCheckFamily.Driver),
        B(0xE6, "DRIVER_VERIFIER_DMA_VIOLATION", "Driver Verifier caught an illegal DMA transfer", "A driver performed a direct-memory-access operation that verifier or the IOMMU rejected. Parameter 1 identifies the violation.", BugCheckFamily.Verifier),
        B(0xE8, "INVALID_CANCEL_OF_FILE_OPEN", "A file open was cancelled invalidly", "A cancel routine was invoked on a file object in an invalid state.", BugCheckFamily.FileSystem),
        B(0xE9, "ACTIVE_EX_WORKER_THREAD_TERMINATION", "A system worker thread was killed", "A worker thread the kernel owns was terminated by other code.", BugCheckFamily.Kernel),
        B(0xEA, "THREAD_STUCK_IN_DEVICE_DRIVER", "A driver stopped responding — usually the graphics driver", "A thread was stuck inside a device driver for too long. On desktop machines this is nearly always the display driver failing to return.", BugCheckFamily.Graphics),
        B(0xEB, "DIRTY_MAPPED_PAGES_CONGESTION", "Modified memory could not be written to disk", "Too many modified pages could not be flushed, usually because storage stopped responding.", BugCheckFamily.Storage),
        B(0xED, "UNMOUNTABLE_BOOT_VOLUME", "Windows could not mount the boot volume", "The boot volume's file system could not be mounted; disk errors and controller mode changes are the usual causes.", BugCheckFamily.Storage),
        B(0xEF, "CRITICAL_PROCESS_DIED", "A process Windows cannot run without stopped", "A critical process terminated. What killed it matters more than the process itself — it is usually the victim of an earlier failure.", BugCheckFamily.Process),
        B(0xF2, "HARDWARE_INTERRUPT_STORM", "A device would not stop interrupting", "A device asserted its interrupt line continuously and its driver would not clear it.", BugCheckFamily.Hardware),
        B(0xF3, "DISORDERLY_SHUTDOWN", "Shutdown failed for lack of memory", "Windows could not complete shutdown because it ran out of memory doing it.", BugCheckFamily.Memory),
        B(0xF4, "CRITICAL_OBJECT_TERMINATION", "A process or thread Windows depends on ended", "A process or thread marked critical terminated unexpectedly. This frequently follows a storage or service failure rather than causing one.", BugCheckFamily.Process),
        B(0xF5, "FLTMGR_FILE_SYSTEM", "The filter manager hit a fatal condition", "The file system filter manager — the layer anti-virus and backup filters plug into — could not continue.", BugCheckFamily.FileSystem),
        B(0xF6, "PCI_VERIFIER_DETECTED_VIOLATION", "PCI verification found a driver fault", "The PCI verifier detected a driver breaking bus rules.", BugCheckFamily.Verifier),
        B(0xF7, "DRIVER_OVERRAN_STACK_BUFFER", "A driver overran a buffer on its stack", "A driver overwrote its own stack past a security cookie — caught by stack protection.", BugCheckFamily.Driver),
        B(0xF9, "DRIVER_RETURNED_STATUS_REPARSE_FOR_VOLUME_OPEN", "A driver returned an invalid result opening a volume", "A driver returned a reparse status for a volume open, which is not permitted.", BugCheckFamily.FileSystem),
        B(0xFA, "HTTP_DRIVER_CORRUPTED", "The kernel HTTP driver was corrupted", "The kernel-mode HTTP driver was found in a corrupt state.", BugCheckFamily.Network),
        B(0xFC, "ATTEMPTED_EXECUTE_OF_NOEXECUTE_MEMORY", "Code ran from memory marked non-executable", "Execution was attempted in memory marked non-executable — a driver defect, or memory corruption redirecting execution.", BugCheckFamily.Driver),
        B(0xFD, "DIRTY_NOWRITE_PAGES_CONGESTION", "Memory that cannot be written out filled up", "Pages that must not be written to disk accumulated until no memory remained.", BugCheckFamily.Memory),
        B(0xFE, "BUGCODE_USB_DRIVER", "A USB driver hit a fatal error", "The USB stack encountered an unrecoverable condition. Parameter 1 identifies which USB rule was broken, and the device or hub involved is worth identifying.", BugCheckFamily.Usb),
        B(0x100, "LOADER_BLOCK_MISMATCH", "Boot loader data did not match the kernel", "The loader block passed to the kernel was invalid or from a mismatched build.", BugCheckFamily.Boot),
        B(0x101, "CLOCK_WATCHDOG_TIMEOUT", "A processor core stopped responding", "A core missed its expected clock interrupt — from the kernel's view it simply stopped. Parameter 4 is the core index. Firmware, power delivery, cooling and CPU stability are all candidates.", BugCheckFamily.Hardware),
        B(0x102, "DPC_WATCHDOG_TIMEOUT", "High-priority kernel work ran too long", "A deferred procedure call exceeded its watchdog time.", BugCheckFamily.Driver),
        B(0x103, "MUP_FILE_SYSTEM", "The network path provider hit a fatal condition", "The multiple UNC provider encountered an unrecoverable state.", BugCheckFamily.Network),
        B(0x104, "AGP_INVALID_ACCESS", "The graphics bus was accessed invalidly", "An invalid access was made to graphics aperture memory.", BugCheckFamily.Graphics),
        B(0x109, "CRITICAL_STRUCTURE_CORRUPTION", "A protected part of Windows was modified", "Kernel Patch Protection found critical kernel code or data changed. Legitimate causes are rare: failing memory, a driver writing wildly, or software that patches the kernel.", BugCheckFamily.Security),
        B(0x10D, "WDF_VIOLATION", "A framework-based driver broke its contract", "The Windows Driver Framework detected a driver using it incorrectly; the framework names the rule broken.", BugCheckFamily.Driver),
        B(0x10E, "VIDEO_MEMORY_MANAGEMENT_INTERNAL", "Graphics memory management hit a fatal error", "The video memory manager encountered an inconsistency it could not continue from.", BugCheckFamily.Graphics),
        B(0x111, "RECURSIVE_NMI", "A hardware interrupt re-entered itself", "A non-maskable interrupt occurred while one was already being handled.", BugCheckFamily.Hardware),
        B(0x113, "VIDEO_DXGKRNL_FATAL_ERROR", "The graphics kernel hit a fatal error", "The DirectX graphics kernel subsystem could not continue. It is the framework, not automatically the culprit — the display miniport driver beneath it usually is.", BugCheckFamily.Graphics),
        B(0x114, "VIDEO_SHADOW_DRIVER_FATAL_ERROR", "The fallback display driver hit a fatal error", "The shadow display driver encountered an unrecoverable condition.", BugCheckFamily.Graphics),
        B(0x116, "VIDEO_TDR_FAILURE", "The graphics card stopped responding and could not be reset", "Windows detected the GPU had stopped, tried to reset the display driver, and the reset failed. Parameter 2 points into the module held responsible.", BugCheckFamily.Graphics),
        B(0x117, "VIDEO_TDR_TIMEOUT_DETECTED", "The graphics card stopped responding", "The display driver did not respond within the timeout and recovery was attempted.", BugCheckFamily.Graphics),
        B(0x119, "VIDEO_SCHEDULER_INTERNAL_ERROR", "The graphics scheduler found a fatal inconsistency", "The video scheduler detected an unrecoverable consistency error, typically reported by the display driver beneath it.", BugCheckFamily.Graphics),
        B(0x11B, "DRIVER_RETURNED_HOLDING_CANCEL_LOCK", "A driver returned still holding a lock", "A driver completed an I/O request without releasing the cancel spin lock.", BugCheckFamily.Driver),
        B(0x11C, "ATTEMPTED_WRITE_TO_CM_PROTECTED_STORAGE", "Code wrote to protected registry storage", "A write was attempted to registry storage the configuration manager protects.", BugCheckFamily.Security),
        B(0x11D, "EVENT_TRACING_FATAL_ERROR", "Event tracing hit a fatal error", "The event tracing subsystem encountered an unrecoverable condition.", BugCheckFamily.Kernel),
        B(0x121, "DRIVER_VIOLATION", "A driver broke a kernel rule", "A driver violated a rule the kernel enforces directly.", BugCheckFamily.Driver),
        B(0x122, "WHEA_INTERNAL_ERROR", "Hardware error reporting itself failed", "The Windows Hardware Error Architecture hit an internal error, often from firmware supplying malformed error data.", BugCheckFamily.Hardware),
        B(0x124, "WHEA_UNCORRECTABLE_ERROR", "The hardware reported an error it could not correct", "A component reported an uncorrectable fault through WHEA. The error record — not the stop code — says whether it was processor cache, memory, PCIe or interconnect.", BugCheckFamily.Hardware),
        B(0x127, "PAGE_NOT_ZERO", "A page that should have been blank was not", "A page expected to contain only zeroes had been modified — a sign of memory corruption or failing RAM.", BugCheckFamily.Memory),
        B(0x12B, "FAULTY_HARDWARE_CORRUPTED_PAGE", "A single-bit memory error was detected", "Windows found a single-bit error in memory. This one does point at hardware — RAM, the memory controller, or instability from overclocking.", BugCheckFamily.Hardware),
        B(0x12C, "EXFAT_FILE_SYSTEM", "The exFAT file system hit a fatal condition", "The exFAT driver encountered a structure it could not handle, commonly on removable media.", BugCheckFamily.FileSystem),
        B(0x133, "DPC_WATCHDOG_VIOLATION", "Kernel work at high priority ran far too long", "Parameter 1 says which: 0 means a single deferred call ran too long, 1 means the system spent too long at dispatch level overall. Storage, network and graphics drivers are the usual sources.", BugCheckFamily.Driver),
        B(0x139, "KERNEL_SECURITY_CHECK_FAILURE", "Windows caught one of its own structures corrupted", "A kernel integrity check failed. Parameter 1 names the category — a corrupted list, a failed bounds check, a stack cookie mismatch. The corruption often happened well before the crash.", BugCheckFamily.Security),
        B(0x13A, "KERNEL_MODE_HEAP_CORRUPTION", "Kernel heap memory was corrupted", "The kernel heap manager found its structures damaged.", BugCheckFamily.Memory),
        B(0x144, "BUGCODE_USB3_DRIVER", "The USB 3 driver hit a fatal error", "The USB 3 stack encountered an unrecoverable condition; the controller, hub or attached device are all worth identifying.", BugCheckFamily.Usb),
        B(0x14A, "KERNEL_AUTO_BOOST_LOCK_ACQUISITION_WITH_RAISED_IRQL", "A lock was taken at the wrong interrupt level", "A boosted lock was acquired at an interrupt level that is not permitted.", BugCheckFamily.Kernel),
        B(0x14C, "FATAL_ABNORMAL_RESET_ERROR", "The system reset abnormally", "Windows recorded an abnormal reset condition.", BugCheckFamily.Hardware),
        B(0x153, "KERNEL_LOCK_ENTRY_LEAKED_ON_THREAD_TERMINATION", "A thread ended still holding a lock", "A thread terminated without releasing a lock entry it owned.", BugCheckFamily.Kernel),
        B(0x154, "UNEXPECTED_STORE_EXCEPTION", "The memory compression store hit an unexpected error", "The store manager — which handles compressed memory and paging — met an exception it did not expect. Storage health, the paging file and memory are the areas to correlate; the name does not prove a failing disk.", BugCheckFamily.Storage),
        B(0x157, "KERNEL_THREAD_PRIORITY_FLOOR_VIOLATION", "Thread priority accounting went wrong", "A thread's priority floor was violated.", BugCheckFamily.Kernel),
        B(0x15B, "HYPERGUARD_VIOLATION", "A kernel integrity guard was tripped", "HyperGuard detected an attempt to modify protected kernel state.", BugCheckFamily.Security),
        B(0x162, "KERNEL_AUTO_BOOST_INVALID_LOCK_RELEASE", "A boosted lock was released invalidly", "A lock tracked by priority boosting was released in an invalid way.", BugCheckFamily.Kernel),
        B(0x18B, "SECURE_KERNEL_ERROR", "The secure kernel hit a fatal error", "The isolated secure kernel used by virtualisation-based security could not continue. Firmware, virtualisation state and low-level drivers are the areas to examine together.", BugCheckFamily.Virtualization),
        B(0x1AA, "EXCEPTION_ON_INVALID_STACK", "An error was raised on a stack that was not valid", "Exception dispatch found the kernel stack pointer outside any valid stack. Parameter 2 names which stack Windows expected, and that is the useful clue.", BugCheckFamily.Kernel),
        B(0x1AB, "UNWIND_ON_INVALID_STACK", "Error unwinding ran onto an invalid stack", "Stack unwinding during exception handling ran off a valid stack.", BugCheckFamily.Kernel),
        B(0x20001, "HYPERVISOR_ERROR", "The hypervisor hit a fatal error", "The Windows hypervisor could not continue safely. This proves a hypervisor-level fatal condition occurred; firmware, CPU and memory stability, and virtualisation state are the areas to examine.", BugCheckFamily.Virtualization),
        B(0xC000021A, "STATUS_SYSTEM_PROCESS_TERMINATED", "A critical Windows service stopped", "A user-mode subsystem Windows cannot run without terminated — usually winlogon or the security subsystem.", BugCheckFamily.Process),
        B(0xC0000218, "STATUS_CANNOT_LOAD_REGISTRY_FILE", "A registry file could not be loaded", "A registry hive could not be read at startup — damaged files or a failing disk.", BugCheckFamily.Storage),
        B(0xDEADDEAD, "MANUALLY_INITIATED_CRASH1", "Someone deliberately crashed this machine", "The crash was triggered on purpose from the debugger. It is not a fault.", BugCheckFamily.Kernel)
    }.ToDictionary(item => item.Code);

    /// <summary>Looks up a stop code. Returns null rather than guessing.</summary>
    public static BugCheckSummary? Find(ulong code) => Catalog.TryGetValue(code, out var summary) ? summary : null;

    public static IReadOnlyCollection<BugCheckSummary> All => (IReadOnlyCollection<BugCheckSummary>)Catalog.Values;

    /// <summary>How many stop codes this build can name. Surfaced in the help pane.</summary>
    public static int Count => Catalog.Count;

    public static string FamilyLabel(BugCheckFamily family) => family switch
    {
        BugCheckFamily.Memory => "Memory",
        BugCheckFamily.Driver => "Driver",
        BugCheckFamily.Storage => "Storage",
        BugCheckFamily.FileSystem => "File system",
        BugCheckFamily.Hardware => "Hardware",
        BugCheckFamily.Graphics => "Graphics",
        BugCheckFamily.Power => "Power",
        BugCheckFamily.Security => "Security / integrity",
        BugCheckFamily.Boot => "Startup",
        BugCheckFamily.Process => "Critical process",
        BugCheckFamily.Network => "Network",
        BugCheckFamily.Usb => "USB",
        BugCheckFamily.Virtualization => "Virtualisation",
        BugCheckFamily.Verifier => "Driver Verifier",
        BugCheckFamily.Kernel => "Kernel",
        _ => "Unclassified"
    };
}
