using System.Globalization;

namespace CrashEvidenceCollector.Core;

/// <summary>
/// Data-driven bugcheck knowledge. Definitions describe only documented semantics;
/// missing or version-dependent parameters deliberately remain Unknown rather than
/// inheriting a generic meaning from their numeric shape.
/// </summary>
public static class BugCheckKnowledge
{
    private const string MicrosoftSource = "Microsoft Windows bugcheck documentation / Windows SDK debugger data";
    private static BugCheckParameterDefinition P(int index, string name, ParameterSemantic semantic, string explanation, IReadOnlyDictionary<ulong, string>? values = null) => new(index, name, semantic, explanation, values);
    private static BugCheckDefinition D(ulong code, string name, string concise, string detailed, BugCheckParameterDefinition[] parameters, string[] commands, string[] patterns, string[] recommendations, string warning) => new(code, name, concise, detailed, parameters, commands, patterns, recommendations, warning, MicrosoftSource);

    private static readonly IReadOnlyDictionary<ulong, BugCheckDefinition> Definitions = new Dictionary<ulong, BugCheckDefinition>
    {
        [0x0A] = D(0x0A, "IRQL_NOT_LESS_OR_EQUAL", "Kernel code accessed invalid or pageable memory at elevated IRQL.", "The fault proves an invalid kernel memory access at an interrupt request level where the access was not permitted; it does not alone identify whether a driver defect, use-after-free, or earlier corruption produced the address.",
            [P(1,"Referenced virtual address",ParameterSemantic.VirtualAddress,"Memory address that could not be accessed."),P(2,"IRQL",ParameterSemantic.Irql,"IRQL at the time of access."),P(3,"Access type",ParameterSemantic.AccessType,"Bit 0 indicates write and bit 3 indicates execute; otherwise read."),P(4,"Instruction pointer",ParameterSemantic.InstructionPointer,"Address of the instruction that attempted the access.")], [".trap where available","r","kv","ln {P4}"], ["faulting instruction","top stack frames","pool or object evidence"], ["Inspect the faulting instruction and nearest non-Microsoft caller.","Compare the same driver across incidents."], "Do not blame ntoskrnl.exe solely because Windows detected the invalid access there."),
        [0x1A] = D(0x1A, "MEMORY_MANAGEMENT", "The memory manager detected corruption or inconsistency in its own structures.", "Parameter 1 selects a documented subtype that determines the meaning of the remaining parameters; page tables, PTEs, working-set lists, or the PFN database were found in a state the memory manager considers impossible. The corrupting party is frequently not the code that detected the corruption.",
            [P(1,"Memory-management subtype",ParameterSemantic.Subtype,"Selects the documented violation layout; the remaining parameters are subtype-specific.",new Dictionary<ulong,string>{{0x31,"Image relocation fix-up table or code corruption"},{0x403,"Page table and PFN database are out of sync"},{0x411,"A page-file-backed PTE is corrupted"},{0x3452,"A PTE in an outswapped process's page tables is corrupted"},{0x3453,"Inconsistent page tables found while deleting an exiting process's address space"},{0x5003,"The working-set free-list is corrupted"},{0x8884,"PFN database element corruption"},{0x8885,"PFN database element corruption"},{0x41284,"A PTE or the working-set list is corrupted"},{0x41790,"A page table page has been corrupted"},{0x41792,"A corrupted PTE has been detected"}}),P(2,"Subtype-specific value",ParameterSemantic.Unknown,"Meaning depends on parameter 1 (often a process object, PTE address, or virtual address); preserve without guessing."),P(3,"Subtype-specific value",ParameterSemantic.Unknown,"Meaning depends on parameter 1."),P(4,"Subtype-specific value",ParameterSemantic.Unknown,"Meaning depends on parameter 1.")], ["!vm","kv","!thread"], ["memory-management subtype","corrupted structure family","repeated corruption across incidents"], ["Decode the subtype before considering components.","Compare the corrupted-structure family across incidents: repeated corruption of different structures suggests a systemic cause rather than one driver."], "Despite the name, MEMORY_MANAGEMENT does not by itself prove defective RAM. Corrupted paging structures can be produced by drivers, storage-backed paging, or CPU/cache instability; the detector is usually the victim."),
        [0x1E] = D(0x1E, "KMODE_EXCEPTION_NOT_HANDLED", "A kernel-mode exception was not handled.", "Parameter 1 is the exception code; the remaining values provide the fault location and exception-specific information where available.",
            [P(1,"Exception code",ParameterSemantic.ExceptionCode,"NTSTATUS/exception code that was not handled."),P(2,"Faulting address",ParameterSemantic.InstructionPointer,"Address where the exception occurred."),P(3,"Exception parameter 0",ParameterSemantic.Unknown,"Exception-specific value."),P(4,"Exception parameter 1",ParameterSemantic.Unknown,"Exception-specific value.")], [".exr -1",".cxr -1","r","kv"], ["exception code","faulting instruction","coherent stack"], ["Decode the exception before assessing nearby drivers."], "An exception occurring in a Microsoft dispatcher does not prove that dispatcher created it."),
        [0x3B] = D(0x3B, "SYSTEM_SERVICE_EXCEPTION", "An exception occurred while executing a system service.", "This commonly records an access violation or illegal instruction crossing a user/kernel service boundary. The process is execution context, not automatic causation.",
            [P(1,"Exception code",ParameterSemantic.ExceptionCode,"Exception that caused the bugcheck."),P(2,"Instruction address",ParameterSemantic.InstructionPointer,"Faulting instruction."),P(3,"Context record",ParameterSemantic.ContextRecord,"CONTEXT structure for the exception."),P(4,"Reserved",ParameterSemantic.Unknown,"Reserved; preserve without interpretation.")], [".cxr {P3}",".exr -1","r","kv","kp","kP"], ["exception operation","faulting instruction","context stack"], ["Inspect the context record and faulting instruction.","Treat PROCESS_NAME as context only."], "Do not label the active application as the cause without kernel evidence."),
        [0x50] = D(0x50, "PAGE_FAULT_IN_NONPAGED_AREA", "Kernel code referenced invalid nonpaged memory.", "The address should have remained valid and resident. A driver, freed object, invalid pointer, or earlier corruption may be involved.",
            [P(1,"Referenced address",ParameterSemantic.VirtualAddress,"Memory address referenced."),P(2,"Access information",ParameterSemantic.AccessType,"Architecture/version-specific access flags."),P(3,"Instruction address",ParameterSemantic.InstructionPointer,"Instruction that referenced memory, when available."),P(4,"Subtype",ParameterSemantic.Subtype,"Internally defined subtype; decode only when known.")], [".trap where available","r","kv","!pte {P1}"], ["address pattern","faulting module","pool evidence"], ["Inspect whether the address resembles null, freed pool, or invalid canonical memory."], "This bugcheck does not by itself prove defective RAM."),
        [0x7E] = D(0x7E, "SYSTEM_THREAD_EXCEPTION_NOT_HANDLED", "A system thread raised an unhandled exception.", "The exception code and records must be interpreted with the restored context and coherent stack.",
            [P(1,"Exception code",ParameterSemantic.ExceptionCode,"Unhandled exception."),P(2,"Exception address",ParameterSemantic.InstructionPointer,"Address where it occurred."),P(3,"Exception record",ParameterSemantic.ExceptionRecord,"EXCEPTION_RECORD pointer."),P(4,"Context record",ParameterSemantic.ContextRecord,"CONTEXT pointer.")], [".exr {P3}",".cxr {P4}","r","kv"], ["exception","restored context","faulting module"], ["Restore both records before assessing module responsibility."], "IMAGE_NAME alone is not proof of origin."),
        [0x7F] = D(0x7F, "UNEXPECTED_KERNEL_MODE_TRAP", "The processor generated a trap the kernel could not handle.", "Parameter 1 identifies the trap number. Double faults and machine checks require processor/stack evidence before attributing hardware or drivers.",
            [P(1,"Trap number",ParameterSemantic.Subtype,"Processor trap number."),P(2,"Reserved or trap-specific",ParameterSemantic.Unknown,"Trap-specific value."),P(3,"Reserved or trap-specific",ParameterSemantic.Unknown,"Trap-specific value."),P(4,"Reserved or trap-specific",ParameterSemantic.Unknown,"Trap-specific value.")], [".trap where available","r","kv","!thread"], ["trap subtype","stack limits","processor state"], ["Inspect the trap subtype and stack coherence."], "A double fault can follow stack exhaustion or corruption; it does not automatically prove CPU failure."),
        [0x9F] = D(0x9F, "DRIVER_POWER_STATE_FAILURE", "A driver failed a power-state transition.", "Parameter 1 selects a documented violation layout. For subtype 3, parameter 4 is the blocked IRP; for subtype 4, parameter 4 points to PnP triage data.",
            [P(1,"Violation type",ParameterSemantic.Subtype,"Selects the parameter layout.",new Dictionary<ulong,string>{{1,"Outstanding power request while freeing device"},{2,"Power IRP sequencing violation"},{3,"Device object blocked a power IRP too long"},{4,"PnP synchronization timeout"}}),P(2,"Device object or timeout",ParameterSemantic.DeviceObject,"Meaning depends on violation type."),P(3,"Device object or triage structure",ParameterSemantic.Address,"Meaning depends on violation type."),P(4,"Blocked IRP or PnP triage",ParameterSemantic.Irp,"For subtype 3 this is the blocked IRP; subtype 4 uses PnP triage data.")], ["!poaction","!irp {P4}","!devstack {P2}","!thread","kv"], ["blocked IRP","device stack owner","power minor function"], ["Identify the blocked IRP owner and device stack before updating or rolling back a driver."], "Do not name a power driver solely because it is loaded."),
        [0xD1] = D(0xD1, "DRIVER_IRQL_NOT_LESS_OR_EQUAL", "A driver accessed invalid memory at elevated IRQL.", "This is the driver-focused counterpart to 0xA; the instruction pointer and restored stack are central evidence.",
            [P(1,"Referenced address",ParameterSemantic.VirtualAddress,"Memory address accessed."),P(2,"IRQL",ParameterSemantic.Irql,"IRQL at access."),P(3,"Access type",ParameterSemantic.AccessType,"Read, write, or execute flags."),P(4,"Instruction pointer",ParameterSemantic.InstructionPointer,"Faulting instruction.")], ["r","kv","ln {P4}"], ["instruction in driver","access operation","repeated driver"], ["Inspect the module containing parameter 4."], "A driver adjacent to the fault is weaker evidence than a faulting instruction inside it."),
        [0x101] = D(0x101, "CLOCK_WATCHDOG_TIMEOUT", "A processor did not receive an expected clock interrupt.", "This indicates a stalled processor/core from the kernel's perspective. Firmware, CPU stability, power, microcode, and low-level execution can be involved.",
            [P(1,"Clock interrupt interval",ParameterSemantic.Flags,"Nominal interval in ticks."),P(2,"Reserved",ParameterSemantic.Unknown,"Reserved."),P(3,"Processor control block",ParameterSemantic.Address,"PRCB address for the unresponsive processor."),P(4,"Processor index",ParameterSemantic.Subtype,"Index of the hung processor.")], ["!prcb {P4}","!running -it","!dpcs","kv"], ["processor index","firmware version","systemic instability"], ["Check BIOS/microcode and test baseline CPU/memory settings when corroborated."], "A watchdog timeout does not alone prove that the physical CPU is defective."),
        [0x116] = D(0x116, "VIDEO_TDR_FAILURE", "Windows failed to reset the display driver after a GPU timeout.", "The graphics stack attempted Timeout Detection and Recovery but could not restore operation.",
            [P(1,"TDR recovery context",ParameterSemantic.Address,"Internal recovery context, if available."),P(2,"Responsible-module address",ParameterSemantic.InstructionPointer,"Pointer into the responsible device-driver module/owner tag."),P(3,"Last operation status",ParameterSemantic.NtStatus,"NTSTATUS from the failed operation, if available."),P(4,"Internal context",ParameterSemantic.Unknown,"Context-dependent data.")], ["ln {P2}","lmvm {MODULE}","kv","!thread"], ["display miniport","dxgkrnl path","graphics live reports"], ["Compare display-driver versions and correlate WATCHDOG/TDR reports."], "dxgkrnl is the recovery framework and is not automatically the origin."),
        [0x124] = D(0x124, "WHEA_UNCORRECTABLE_ERROR", "WHEA reported an uncorrectable hardware error.", "The WHEA error record identifies whether the report concerns processor cache, memory, PCIe, interconnect, or another source. The stop code alone is insufficient to name a component.",
            [P(1,"Error source",ParameterSemantic.Subtype,"WHEA source type."),P(2,"WHEA error record",ParameterSemantic.WheaErrorRecord,"Address of WHEA_ERROR_RECORD where defined."),P(3,"MCi_STATUS high",ParameterSemantic.Flags,"High 32 bits for MCA machine checks."),P(4,"MCi_STATUS low",ParameterSemantic.Flags,"Low 32 bits for MCA machine checks.")], ["!errrec {P2}","!sysinfo cpuinfo","kv"], ["error record section","MCA bank/status","PCIe identity"], ["Use !errrec classification before hardware recommendations."], "Do not declare the CPU defective merely because a machine-check record exists."),
        [0x133] = D(0x133, "DPC_WATCHDOG_VIOLATION", "High-IRQL work exceeded the watchdog threshold.", "The subtype determines whether a single DPC/ISR ran too long or cumulative time was excessive.",
            [P(1,"Violation type",ParameterSemantic.Subtype,"0 indicates one DPC/ISR timeout; 1 indicates cumulative DISPATCH_LEVEL time."),P(2,"Watchdog period",ParameterSemantic.Flags,"Period or timeout value."),P(3,"Triage block",ParameterSemantic.Address,"DPC watchdog triage data when available."),P(4,"Reserved",ParameterSemantic.Unknown,"Reserved." )], ["!dpcs","!timer","!stacks 2","kv"], ["long-running DPC","ISR module","storage/network/graphics path"], ["Identify the DPC/ISR owner before changing drivers."], "A busy application does not directly execute kernel DPCs."),
        [0x139] = D(0x139, "KERNEL_SECURITY_CHECK_FAILURE", "The kernel detected corruption of a critical structure.", "Parameter 1 describes a fast-fail or corruption category; the trap and exception records provide context.",
            [P(1,"Corruption type",ParameterSemantic.Subtype,"Fast-fail/list/cookie or other documented category."),P(2,"Trap frame",ParameterSemantic.TrapFrame,"Trap frame for the failure."),P(3,"Exception record",ParameterSemantic.ExceptionRecord,"Exception record."),P(4,"Reserved",ParameterSemantic.Unknown,"Reserved." )], [".trap {P2}",".exr {P3}","r","kv"], ["fast-fail subtype","list owner","faulting callback"], ["Inspect the documented subtype and last coherent frames."], "Detected corruption may have occurred earlier than the crash location."),
        [0x154] = D(0x154, "UNEXPECTED_STORE_EXCEPTION", "The kernel store component encountered an unexpected exception.", "Storage, paging, filesystem, filter, and memory evidence should be correlated; the name does not by itself prove a physical disk failure.",
            [P(1,"Store context",ParameterSemantic.Address,"Store-manager context."),P(2,"Exception information",ParameterSemantic.Address,"Internal exception information."),P(3,"Reserved",ParameterSemantic.Unknown,"Preserve raw value."),P(4,"Reserved",ParameterSemantic.Unknown,"Preserve raw value.")], [".exr -1",".cxr -1","kv","!blackboxntfs","!blackboxstorage"], ["storage events","paging errors","filter stack"], ["Correlate disk/NTFS/Storport evidence and page-file placement."], "Healthy status is not proof that every SMART attribute is healthy."),
        [0x1AA] = D(0x1AA, "EXCEPTION_ON_INVALID_STACK", "Exception dispatch crossed onto an invalid kernel stack.", "The kernel's stack pointer or expected stack limits were invalid during exception dispatch/unwind. Context and exception records are explicitly supplied by the bugcheck.",
            [P(1,"Current stack pointer",ParameterSemantic.Address,"Pointer to the current invalid stack."),P(2,"Expected stack-limit type",ParameterSemantic.StackLimitType,"Kernel's best estimate of the stack category.",new Dictionary<ulong,string>{{0,"Bugcheck stack"},{1,"Processor DPC stack"},{2,"Expanded kernel callout stack"},{3,"Normal kernel thread stack"},{4,"Thread context-swap stack"},{5,"win32k kernel/user callout stack"},{6,"Processor ISR stack"},{7,"Kernel debugger stack"},{8,"Processor NMI stack"},{9,"Processor machine-check stack"},{10,"Processor exception stack"}}),P(3,"Context record",ParameterSemantic.ContextRecord,"Context being unwound or used for exception dispatch."),P(4,"Exception record",ParameterSemantic.ExceptionRecord,"Active exception record.")], [".cxr {P3}",".exr {P4}","r","kv","kp","kP","!thread"], ["stack-limit warning","context exception","last coherent frames"], ["Restore context and exception records, then identify the last coherent stack transition."], "Invalid stack evidence supports corruption or illegal stack use, but does not alone prove defective RAM or that the active process caused it."),
        [0x1E6] = D(0x1E6, "DRIVER_VERIFIER_DMA_VIOLATION", "Driver Verifier or IOMMU detected an illegal DMA operation.", "DMA verification data can identify a device/driver relationship. Parameter layouts can vary by violation type and OS version.",
            [P(1,"Violation type",ParameterSemantic.Subtype,"DMA violation subtype."),P(2,"Device or context",ParameterSemantic.Address,"Subtype-dependent device/context."),P(3,"Fault information",ParameterSemantic.Address,"Subtype-dependent information."),P(4,"Fault information",ParameterSemantic.Address,"Subtype-dependent information.")], ["!analyze -v","!verifier","!devstack where identified","kv"], ["verifier naming","IOMMU fault","device stack"], ["Use verifier/IOMMU output to identify an exact non-Microsoft driver."], "Do not generalize a DMA violation to unrelated drivers."),
        [0xEF] = D(0xEF, "CRITICAL_PROCESS_DIED", "A process essential to Windows terminated.", "The process object identifies what died; the reason it died may require user-mode dump, storage, service, or corruption evidence.",
            [P(1,"Critical process object",ParameterSemantic.Address,"Process object that terminated."),P(2,"Process or thread indicator",ParameterSemantic.Subtype,"Nonzero may indicate a critical thread."),P(3,"Process object",ParameterSemantic.Address,"Related process object where supplied."),P(4,"Additional information",ParameterSemantic.Unknown,"Version-dependent information.")], ["!process {P1} 1","!thread","kv"], ["critical process","termination status","storage/service evidence"], ["Identify the terminated component and preceding error rather than treating it as the root cause."], "The critical process is often the victim of an earlier failure."),
        [0xF4] = D(0xF4, "CRITICAL_OBJECT_TERMINATION", "A critical process or thread terminated.", "The object type and object pointers identify what Windows considered critical; external cause requires more evidence.",
            [P(1,"Object type",ParameterSemantic.Subtype,"Process or thread selector."),P(2,"Terminating object",ParameterSemantic.Address,"Object being terminated."),P(3,"Process image",ParameterSemantic.Address,"Image-name pointer where supplied."),P(4,"Additional information",ParameterSemantic.Unknown,"Version-dependent." )], ["!process {P2} 1","!thread {P2}","kv"], ["termination status","storage/paging","service failure"], ["Correlate process termination with storage and system events."], "A named critical process can be a victim rather than cause."),
        [0x18B] = D(0x18B, "SECURE_KERNEL_ERROR", "The secure kernel encountered a fatal error.", "VBS, secure-kernel, firmware, hypervisor, and low-level driver evidence should be examined together.",
            [P(1,"Secure-kernel status",ParameterSemantic.Unknown,"Version-dependent secure-kernel value."),P(2,"Context",ParameterSemantic.Address,"Version-dependent context."),P(3,"Context",ParameterSemantic.Address,"Version-dependent context."),P(4,"Context",ParameterSemantic.Address,"Version-dependent context.")], ["vertarget","!sysinfo smbios","kv","lm"], ["VBS status","firmware","virtualization modules"], ["Correlate VBS state with BIOS/chipset and repeated incidents."], "Normal VBS activity is not evidence of a defect."),
        [0x20001] = D(0x20001, "HYPERVISOR_ERROR", "The Windows hypervisor encountered a fatal error.", "The hypervisor could not continue safely. Firmware, CPU/memory stability, virtualization state, and low-level components are possible areas; parameters are version-specific unless debugger output provides a subtype.",
            [P(1,"Hypervisor status",ParameterSemantic.Subtype,"Version-specific hypervisor error information."),P(2,"Hypervisor context",ParameterSemantic.Unknown,"Preserve for debugger correlation."),P(3,"Hypervisor context",ParameterSemantic.Unknown,"Preserve for debugger correlation."),P(4,"Hypervisor context address",ParameterSemantic.Address,"Version-specific context/address." )], ["vertarget","!sysinfo smbios","!sysinfo cpuinfo","r","kv","lm"], ["hypervisor stack","VBS state","firmware version","repeat pattern"], ["Inspect BIOS/chipset updates and test baseline CPU/memory settings only when evidence supports instability."], "Normal Hyper-V initialization events do not prove the hypervisor caused a crash; the bugcheck itself does prove a hypervisor fatal condition occurred.")
    };

    public static BugCheckDefinition? Find(ulong code) => Definitions.TryGetValue(code, out var definition) ? definition : null;
    public static IReadOnlyCollection<BugCheckDefinition> All => Definitions.Values.ToList();

    public static IReadOnlyList<DecodedParameter> DecodeParameters(ulong code, IReadOnlyList<string> rawParameters)
    {
        var definition = Find(code);
        var result = new List<DecodedParameter>();
        for (var index = 0; index < Math.Min(4, rawParameters.Count); index++)
        {
            var raw = rawParameters[index];
            var parameter = definition?.Parameters.FirstOrDefault(item => item.Index == index + 1) ?? P(index + 1, $"Parameter {index + 1}", ParameterSemantic.Unknown, "No documented local definition is available; preserve without guessing.");
            NumericParser.TryParse(raw, out var value);
            var symbolic = parameter.Values is not null && parameter.Values.TryGetValue(value, out var named) ? named : parameter.Semantic switch
            {
                ParameterSemantic.AccessType => DecodeAccess(value),
                ParameterSemantic.ExceptionCode or ParameterSemantic.NtStatus => TypedCodeDecoders.DecodeNtStatus(value)?.Name,
                _ => null
            };
            result.Add(new(index + 1, raw, parameter.Name, parameter.Explanation, $"0x{value:X16} / {value.ToString("N0", CultureInfo.InvariantCulture)}", parameter.Semantic, parameter.Semantic is not (ParameterSemantic.Address or ParameterSemantic.VirtualAddress or ParameterSemantic.InstructionPointer or ParameterSemantic.TrapFrame or ParameterSemantic.ContextRecord or ParameterSemantic.ExceptionRecord or ParameterSemantic.Irp or ParameterSemantic.DeviceObject or ParameterSemantic.WheaErrorRecord) || NumericParser.IsCanonicalAddress(value), symbolic));
        }
        return result;
    }

    private static string DecodeAccess(ulong value) => (value & 8) != 0 ? "Execute" : (value & 1) != 0 ? "Write" : "Read";
}

public static class NumericParser
{
    public static bool TryParse(string? raw, out ulong value)
    {
        value = 0; if (string.IsNullOrWhiteSpace(raw)) return false;
        var text = raw.Trim().Replace("`", string.Empty).Replace("_", string.Empty);
        return text.StartsWith("0x", StringComparison.OrdinalIgnoreCase) ? ulong.TryParse(text[2..], NumberStyles.HexNumber, CultureInfo.InvariantCulture, out value) : ulong.TryParse(text, NumberStyles.HexNumber, CultureInfo.InvariantCulture, out value);
    }

    public static bool IsCanonicalAddress(ulong value)
    {
        if (value == 0) return false;
        var top = value >> 48;
        return top == 0 || top == 0xFFFF;
    }
}
